
#配置数据库
spring:
  datasource:
      username: root
      password: zdkj12345
      #serverTimezone=UTC 配置时区
      url: jdbc:mysql://127.0.0.1:3306/Schame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
#mybatis
#http://localhost:8080/swagger-ui.html
mybatis-plus:
  mapper-locations: classpath:com/hufei/springbootttemp/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hufei.springboottemp.model
  configuration.jdbc-type-for-null: null
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  NONE:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID", AUTO: MP自动决定;
      id-type: UUID
      #字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #table-prefix: sys_
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
    # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#Tomcat端口
server:
  port: 8080